DROP TABLE IF EXISTS HOTEL;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS USER;

CREATE TABLE HOTEL
(
  id VARCHAR AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  lat long NOT NULL,
  lon long NOT NULL
);

CREATE TABLE ADDRESS
(
  pincode INT AUTO_INCREMENT PRIMARY KEY,
  city VARCHAR(15),
  country VARCHAR(15)
);

CREATE TABLE USER
(
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  pincode INT
  --FOREIGN KEY (pincode) REFERENCES ADDRESS(pincode)
);
